import type { Metadata } from "next";

import "./globals.css";
import Providers from "./providers";
import BottomNav from "@/components/bottom-nav/BottomNav";
import localFont from "next/font/local";

const satoshi = localFont({
  src: "../../public/fonts/Satoshi-Regular.woff2",
  variable: "--font-satoshi",
  display: "swap",
});

const bevellier = localFont({
  src: "../../public/fonts/Bevellier-Medium.woff2",
  variable: "--font-bevellier",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${satoshi.variable} ${bevellier.variable}`}>
      <body>
        <Providers>
          {children}
          <BottomNav />
        </Providers>
      </body>
    </html>
  );
}
